<a href="https://colab.research.google.com/github/Sanjeeviit/Business-Analytics/blob/main/BAASSIGNMENT3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


# Load training data
X_train = pd.read_excel("/content/X_train.xlsx")
y_train = pd.read_excel("/content/Y_train.xlsx")

# Ensure that y_train is a 1D array
y_train = y_train.iloc[:, 0]

# Load test data
X_test = pd.read_excel("/content/X_test.xlsx")
y_test = pd.read_excel("/content/Y_test.xlsx")






# Ensure that y_test is a 1D array
y_test = y_test.iloc[:, 0]




In [47]:
X_train.head()

Unnamed: 0  age  gender  chest_pain  rest_bps  cholestrol  \
0          49   53       0           0       138         234   
1         171   48       1           1       110         229   
2         223   56       0           0       200         288   
3          58   34       1           3       118         182   
4         154   39       0           2       138         220   

   fasting_blood_sugar  rest_ecg  thalach  exer_angina  old_peak  slope  ca  \
0                    0         0      160            0       0.0      2   0   
1                    0         1      168            0       1.0      0   0   
2                    1         0      133            1       4.0      0   2   
3                    0         0      174            0       0.0      2   0   
4                    0         1      152            0       0.0      1   0   

   thalassemia  
0            2  
1            3  
2            3  
3            2  
4            2

In [48]:
X_train = X_train.drop(columns ='Unnamed: 0')

In [49]:
X_train.head()

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0   53       0           0       138         234                    0   
1   48       1           1       110         229                    0   
2   56       0           0       200         288                    1   
3   34       1           3       118         182                    0   
4   39       0           2       138         220                    0   

   rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  
0         0      160            0       0.0      2   0            2  
1         1      168            0       1.0      0   0            3  
2         0      133            1       4.0      0   2            3  
3         0      174            0       0.0      2   0            2  
4         1      152            0       0.0      1   0            2

In [50]:
y_test.shape

(91,)

In [51]:
X_train.shape

(212, 13)

In [53]:
X_test = X_test.drop(columns ='Unnamed: 0')

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Initialize Logistic Regression model
model = LogisticRegression(random_state=17)

# Fit the model on training data
model.fit(X_train, y_train)

# Predict on training data
y_pred_train = model.predict(X_train)

# Calculate training accuracy
training_accuracy = accuracy_score(y_train, y_pred_train)

# Print the training accuracy
print("Training Accuracy:", training_accuracy)


Training Accuracy: 1.0


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [56]:
from sklearn.metrics import confusion_matrix

# Make predictions on the test data
Y_pred_test = model.predict(X_test)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, Y_pred_test)

# Extract false positive count
false_positives = conf_matrix[0, 1]

# Print the number of false positives
print("Number of false positives:", false_positives)


Number of false positives: 0


In [60]:
from sklearn.metrics import confusion_matrix

# Make predictions on the test data
y_pred_test = model.predict(X_test)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_test)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [58]:
from sklearn.metrics import precision_score

# Calculate precision for class 0 (patients without heart disease)
precision_class_0 = precision_score(y_train, y_pred_train, pos_label=0)

# Print the precision for class 0
print("Precision for patients without heart disease:", precision_class_0)




ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [ ]:
X_test.shape

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
X_train.shape
X_test.shape




In [ ]:
X_train.shape

In [ ]:
X_test_scaled


In [ ]:
X_train_scaled

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_reg =LogisticRegression(random_state =17).fit(X_train_scaled,y_train)

In [ ]:
log_reg.predict(X_train_scaled)

In [ ]:
log_reg.score(X_train_scaled,y_train)

In [ ]:
log_reg =LogisticRegression(random_state =17).fit(X_test_scaled,y_test)

In [ ]:
log_reg.score(X_test_scaled,y_test)

In [ ]:
log_reg.score(X_test,y_test)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as sc
import sklearn as sk
import seaborn as sns
!pip install pyreadstat